# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orz_app', '0002_auto_20171023_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=255)),
                ('blog_comment', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orz_app.Article')),
            ],
        ),
    ]
