# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orz_app', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_comment',
            field=models.CharField(max_length=1024),
        ),
    ]
