# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orz_app', '0009_auto_20171031_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
